#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
	mode http
        default_backend http_back

backend web-backend
        balance roundrobin
	mode http
        server 169356-web-01 35.153.67.221:80 check
        server 169356-web-02 54.90.43.152:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
