#!/usr/bin/env bash
# Bash script that displays lines containing the bash word, thus allowing
  you to easily get the PID of your Bash process. You cannot use pgrep

./1-list_your_processes | grep "bash"
